[package]
name = "audio-resampler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.0" # for reading/writing audio files
rubato = "0.12.0" # for resampling
rayon = "1.7.0" # for parallel processing
